"""
IP-SAKTI Sahayak / JurifyLaw: Authoritative Ayush & Patent Legal Corpus
Authoritative statutory references for Ayurvedic Intellectual Property,
Regulatory Licensing, and Biodiversity Access & Benefit Sharing (ABS).
Target collection: ayush_legal_corpus
"""

from typing import List, Dict, Any

STATUTORY_CORPUS: List[Dict[str, Any]] = [
    {
        "id": "patents_act_1970",
        "title": "The Patents Act, 1970 (as amended)",
        "shortTitle": "Patents Act 1970",
        "actRegulation": "The Patents Act, 1970 & Patents Rules, 2003 (as amended)",
        "jurisdiction": "India",
        "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
        "sourceUrl": "https://ipindia.gov.in",
        "version": "Act No. 39 of 1970 (incorporating Patents Rules 2024)",
        "year": "1970",
        "effectiveDate": "1972-04-20",
        "lastAmendedDate": "2024-03-15",
        "isLoaded": True,
        "sectionsCovered": ["Section 3(p)", "Section 3(e)", "Section 3(d)", "Section 10(4)(d)(ii)", "Section 25 & 64"],
        "sections": [
            {
                "section": "Section 3(p)",
                "sectionNumber": "Section 3(p)",
                "title": "Traditional Knowledge Non-Patentability Bar",
                "heading": "Traditional Knowledge Non-Patentability Bar",
                "text": "An invention which in effect is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components is not an invention within the meaning of this Act.",
                "keywords": ["section 3(p)", "3p", "traditional knowledge", "tkdl", "prior art", "samhita", "charaka", "sushruta", "ayurveda", "non-patentable", "ayush classical", "पारंपरिक ज्ञान", "पारंपारिक ज्ञान"],
                "relevance": "Absolute statutory bar preventing patents on classical recipes or known herbal uses documented in Ayurvedic texts.",
                "practicalImpact": "Formulations documented in the First Schedule Samhitas cannot be patented as products in India.",
                "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
                "sourceUrl": "https://ipindia.gov.in",
                "version": "Act No. 39 of 1970 (s. 3(p) inserted by Act 38 of 2002)",
                "effectiveDate": "2003-05-20",
                "lastAmendedDate": "2024-03-15"
            },
            {
                "section": "Section 3(e)",
                "sectionNumber": "Section 3(e)",
                "title": "Mere Admixture / Synergistic Activity Mandate",
                "heading": "Mere Admixture / Synergistic Activity Mandate",
                "text": "A substance obtained by a mere admixture resulting only in the aggregation of the properties of the components thereof or a process for producing such substance is not patentable without conclusive scientific demonstration of synergistic therapeutic efficacy.",
                "keywords": ["section 3(e)", "3e", "mere admixture", "synergy", "synergistic", "aggregation", "combination", "isobologram", "herbal mix", "efficacy", "सिनर्जी", "मिश्रण"],
                "relevance": "Polyherbal combinations must prove statistical and experimental synergy (greater than additive effect) to overcome 3(e) objections.",
                "practicalImpact": "Applicant must provide in-vitro/in-vivo synergistic data (e.g., Combination Index < 1.0) showing mutual potentiation.",
                "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
                "sourceUrl": "https://ipindia.gov.in",
                "version": "Act No. 39 of 1970",
                "effectiveDate": "1972-04-20",
                "lastAmendedDate": "2024-03-15"
            },
            {
                "section": "Section 3(d)",
                "sectionNumber": "Section 3(d)",
                "title": "New Form of Known Substance / Incremental Efficacy",
                "heading": "New Form of Known Substance / Incremental Efficacy",
                "text": "The mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance, or the mere discovery of any new property or new use for a known substance, is not patentable.",
                "keywords": ["section 3(d)", "3d", "new form", "efficacy", "bioavailability", "nanoparticle", "extract", "derivative", "phytopharmaceutical"],
                "relevance": "Novel delivery forms (e.g. phyto-liposomes, nano-curcumin) must demonstrate therapeutic efficacy enhancement over classical extract.",
                "practicalImpact": "Increased bioavailability alone is insufficient unless accompanied by clinically proven therapeutic efficacy improvements.",
                "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
                "sourceUrl": "https://ipindia.gov.in",
                "version": "Act No. 39 of 1970 (amended by Act 15 of 2005)",
                "effectiveDate": "2005-01-01",
                "lastAmendedDate": "2024-03-15"
            },
            {
                "section": "Section 10(4)(d)(ii)",
                "sectionNumber": "Section 10(4)(d)(ii)",
                "title": "Mandatory Biological Resource Origin Disclosure",
                "heading": "Mandatory Biological Resource Origin Disclosure",
                "text": "Every complete specification must disclose the source and geographical origin of the biological material in the specification, when that material is used for the invention.",
                "keywords": ["section 10", "disclosure of origin", "geographical origin", "source of biological material", "bda clearance", "specification"],
                "relevance": "Failure to disclose the geographic origin of Indian botanical or biological materials renders the patent liable for rejection or revocation.",
                "practicalImpact": "Exact collection state/district in India must be cited in the patent application description.",
                "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
                "sourceUrl": "https://ipindia.gov.in",
                "version": "Act No. 39 of 1970 (amended by Act 38 of 2002)",
                "effectiveDate": "2003-05-20",
                "lastAmendedDate": "2024-03-15"
            },
            {
                "section": "Section 25 & 64",
                "sectionNumber": "Section 25 & 64",
                "title": "Opposition & Revocation on Traditional Knowledge Grounds",
                "heading": "Opposition & Revocation on Traditional Knowledge Grounds",
                "text": "Section 25(1)(k) and 64(1)(p) allow pre-grant and post-grant opposition as well as revocation of a patent if the complete specification does not disclose or wrongly mentions the source or geographical origin of biological material, or if the invention was anticipated having regard to traditional knowledge.",
                "keywords": ["revocation", "opposition", "tkdl challenge", "prior art anticipation", "section 64", "section 25"],
                "relevance": "CSIR/TKDL regularly files pre-grant third-party observations based on Samhita citations against vulnerable patent claims.",
                "practicalImpact": "Competitors or public bodies can challenge invalid traditional knowledge patents free of official fee under Section 25(1).",
                "authority": "Office of the Controller General of Patents, Designs and Trade Marks (CGPDTM)",
                "sourceUrl": "https://ipindia.gov.in",
                "version": "Act No. 39 of 1970 (incorporating 2005 Amendments)",
                "effectiveDate": "2005-01-01",
                "lastAmendedDate": "2024-03-15"
            }
        ]
    },
    {
        "id": "biological_diversity_act_2002",
        "title": "Biological Diversity Act, 2002 (as amended by 2023 Amendment Act)",
        "shortTitle": "Biological Diversity Act 2002/2023",
        "actRegulation": "Biological Diversity Act, 2002 & Biological Diversity (Amendment) Act, 2023",
        "jurisdiction": "India & International",
        "authority": "National Biodiversity Authority (NBA, Chennai) & State Biodiversity Boards (SBB)",
        "sourceUrl": "http://nbaindia.org",
        "version": "Act No. 18 of 2003 / Amendment Act No. 10 of 2023",
        "year": "2002",
        "effectiveDate": "2003-10-01",
        "lastAmendedDate": "2024-04-01",
        "isLoaded": True,
        "sectionsCovered": ["Section 3", "Section 6", "Section 7", "Section 40 & NTAC"],
        "sections": [
            {
                "section": "Section 3",
                "sectionNumber": "Section 3",
                "title": "Access to Biological Resources by Foreign Entities (Form I)",
                "heading": "Access to Biological Resources by Foreign Entities (Form I)",
                "text": "No person who is not a citizen of India, or a body corporate, association or organization not incorporated or registered in India, or having non-Indian participation in share capital or management, shall obtain any biological resource occurring in India or associated knowledge without approval of the National Biodiversity Authority.",
                "keywords": ["section 3", "nba approval", "foreign entity", "fdi", "nri", "foreign equity", "form i", "biological resource", "foreign participation", "जैव विविधता"],
                "relevance": "Startups or companies with any foreign director, shareholder, or non-Indian holding must seek mandatory Form I approval from NBA.",
                "practicalImpact": "Failure to obtain NBA prior approval attracts statutory penalties and blocks product commercialization.",
                "authority": "National Biodiversity Authority (NBA, Chennai)",
                "sourceUrl": "http://nbaindia.org",
                "version": "Act No. 18 of 2003 (as amended by Act 10 of 2023)",
                "effectiveDate": "2003-10-01",
                "lastAmendedDate": "2024-04-01"
            },
            {
                "section": "Section 6",
                "sectionNumber": "Section 6",
                "title": "Prior Approval for Intellectual Property Rights (Form III)",
                "heading": "Prior Approval for Intellectual Property Rights (Form III)",
                "text": "No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India without obtaining the prior approval of the National Biodiversity Authority before grant of patent (Form III).",
                "keywords": ["section 6", "form iii", "ip approval", "patent grant", "nba form 3", "patent office clearance", "ip clearance", "फॉर्म 3"],
                "relevance": "The Indian Patent Office cannot grant a patent until the applicant submits NBA Form III clearance.",
                "practicalImpact": "Applicants must file Form III with NBA promptly after patent filing and before the patent application proceeds to grant.",
                "authority": "National Biodiversity Authority (NBA, Chennai)",
                "sourceUrl": "http://nbaindia.org",
                "version": "Act No. 18 of 2003 (amended 2023)",
                "effectiveDate": "2003-10-01",
                "lastAmendedDate": "2024-04-01"
            },
            {
                "section": "Section 7",
                "sectionNumber": "Section 7",
                "title": "Prior Intimation to State Biodiversity Board (SBB) for Indian Entities",
                "heading": "Prior Intimation to State Biodiversity Board (SBB) for Indian Entities",
                "text": "No person who is a citizen of India or a body corporate registered in India shall obtain any biological resource for commercial utilization except after giving prior intimation to the State Biodiversity Board concerned (excluding local vaids, hakims, and registered Ayush practitioners).",
                "keywords": ["section 7", "sbb intimation", "commercial utilization", "state biodiversity board", "indian company", "ayurvedic manufacturer", "एसबीबी"],
                "relevance": "Indian Ayush manufacturers must intimate the relevant State Biodiversity Board before commercial manufacture.",
                "practicalImpact": "Subject to Access and Benefit Sharing (ABS) fees ranging from 0.1% to 0.5% of ex-factory sale price.",
                "authority": "State Biodiversity Boards (SBB)",
                "sourceUrl": "http://nbaindia.org",
                "version": "Act No. 18 of 2003 (amended 2023)",
                "effectiveDate": "2003-10-01",
                "lastAmendedDate": "2024-04-01"
            },
            {
                "section": "Section 40 & NTAC",
                "sectionNumber": "Section 40 & NTAC",
                "title": "Normally Traded as Commodities (NTAC) Exemption",
                "heading": "Normally Traded as Commodities (NTAC) Exemption",
                "text": "The Central Government exempts by official notification biological resources normally traded as commodities (NTAC) from the provisions of access regulations when traded strictly as commodities and not for research or bioprospecting.",
                "keywords": ["section 40", "ntac", "normally traded as commodities", "exemption", "commodity trade", "spices", "raw herb exemption"],
                "relevance": "Over 400 Indian medicinal plant raw parts traded as open commodities are exempt from NBA approval if purchased for pure trade/consumption.",
                "practicalImpact": "Direct purchases of notified NTAC herbs from certified wholesale agricultural mandis bypass bioprospecting permissions.",
                "authority": "Ministry of Environment, Forest and Climate Change (MoEFCC)",
                "sourceUrl": "http://nbaindia.org",
                "version": "MoEFCC NTAC Notifications (Codified 2024)",
                "effectiveDate": "2016-04-07",
                "lastAmendedDate": "2024-04-01"
            }
        ]
    },
    {
        "id": "drugs_and_cosmetics_act_1940",
        "title": "Drugs and Cosmetics Act, 1940 & Rules 1945 (Ayush Provisions)",
        "shortTitle": "Drugs & Cosmetics Act 1940",
        "actRegulation": "Drugs and Cosmetics Act, 1940 & Rules 1945 (Chapters IV-A & VII)",
        "jurisdiction": "India",
        "authority": "State Ayush Licensing Authorities (SLA)",
        "sourceUrl": "https://ayush.gov.in",
        "version": "Act No. 23 of 1940 & Rules 1945 (Ayush Codified 2026)",
        "year": "1940",
        "effectiveDate": "1947-04-01",
        "lastAmendedDate": "2022-10-14",
        "isLoaded": True,
        "sectionsCovered": ["Section 3(a)", "Section 3(h)", "Schedule T", "Rule 158B"],
        "sections": [
            {
                "section": "Section 3(a)",
                "sectionNumber": "Section 3(a)",
                "title": "Classical Ayurvedic, Siddha or Unani Drug Definition",
                "heading": "Classical Ayurvedic, Siddha or Unani Drug Definition",
                "text": "Ayurvedic, Siddha or Unani drug includes all medicines intended for internal or external use for diagnosis, treatment, mitigation or prevention of disease in human beings or animals, manufactured exclusively in accordance with the formulae in authoritative books specified in the First Schedule.",
                "keywords": ["section 3(a)", "classical drug", "first schedule", "samhita", "authoritative text", "form 25d", "classical ayurveda", "shastra", "पारंपरिक औषध"],
                "relevance": "Must strictly adhere to classical composition and processing. No clinical trial required; reference to First Schedule Samhita suffices.",
                "practicalImpact": "Direct licensing pathway via State Ayush Licensing Authority with proof of First Schedule textual formula.",
                "authority": "State Ayush Licensing Authorities (SLA)",
                "sourceUrl": "https://ayush.gov.in",
                "version": "Act No. 23 of 1940 (Chapter IV-A inserted by Act 13 of 1964)",
                "effectiveDate": "1964-06-10",
                "lastAmendedDate": "2022-10-14"
            },
            {
                "section": "Section 3(h)",
                "sectionNumber": "Section 3(h)",
                "title": "Ayurvedic Patent or Proprietary Medicine",
                "heading": "Ayurvedic Patent or Proprietary Medicine",
                "text": "A formulation containing ingredients cited in authoritative Ayurvedic texts but formulated in a proportion, vehicle, or dosage form not identical to classical texts.",
                "keywords": ["section 3(h)", "proprietary medicine", "ayurvedic proprietary", "ayush patent medicine", "rule 158b", "safety data", "novel formulation", "प्रोपायटरी"],
                "relevance": "Covers innovative Ayurvedic preparations (capsules, syrups, modern extracts). Requires safety and efficacy documentation under Rule 158B.",
                "practicalImpact": "Eligible for trademark and potentially patent (if proven synergistic under 3(e)). Must obtain proprietary SLA license.",
                "authority": "State Ayush Licensing Authorities (SLA)",
                "sourceUrl": "https://ayush.gov.in",
                "version": "Act No. 23 of 1940 (amended by Act 68 of 1982)",
                "effectiveDate": "1983-02-01",
                "lastAmendedDate": "2022-10-14"
            },
            {
                "section": "Schedule T",
                "sectionNumber": "Schedule T",
                "title": "Good Manufacturing Practices (GMP) for Ayush",
                "heading": "Good Manufacturing Practices (GMP) for Ayush",
                "text": "Mandatory Good Manufacturing Practices (GMP) for manufacture of Ayurvedic, Siddha and Unani drugs: specifies factory premises hygiene, raw material testing, reference standards, stability data, and batch records.",
                "keywords": ["schedule t", "gmp", "manufacturing license", "quality control", "heavy metal testing", "batch testing", "ayush factory", "शेड्यूल टी"],
                "relevance": "Every manufacturing unit must obtain Schedule T GMP certification from the State Licensing Authority.",
                "practicalImpact": "Requires validated testing for heavy metals (lead, arsenic, cadmium, mercury), pesticide residues, and microbial load.",
                "authority": "State Licensing Authority",
                "sourceUrl": "https://ayush.gov.in",
                "version": "Drugs and Cosmetics Rules 1945 (Schedule T inserted by GSR 560(E))",
                "effectiveDate": "2000-06-23",
                "lastAmendedDate": "2022-10-14"
            },
            {
                "section": "Rule 158B",
                "sectionNumber": "Rule 158B",
                "title": "Evidence of Safety and Efficacy for Ayush Proprietary Licensing",
                "heading": "Evidence of Safety and Efficacy for Ayush Proprietary Licensing",
                "text": "Requires proof of safety, trial data, or published scientific literature for patent or proprietary Ayurvedic formulations depending on whether ingredients are used for classical or newly claimed indications.",
                "keywords": ["rule 158b", "proof of efficacy", "safety trial", "published literature", "pilot clinical study", "proprietary approval", "नियम 158b"],
                "relevance": "New combinations with non-classical claims require safety pharmacology studies and clinical efficacy documentation.",
                "practicalImpact": "Determines whether laboratory pilot trials or existing textual safety references will be required for marketing approval.",
                "authority": "State Ayush Licensing Authorities (SLA)",
                "sourceUrl": "https://ayush.gov.in",
                "version": "Drugs and Cosmetics Rules 1945 (Rule 158B inserted by GSR 663(E))",
                "effectiveDate": "2008-09-17",
                "lastAmendedDate": "2022-10-14"
            }
        ]
    },
    {
        "id": "ayurveda_aahar_regulations_2022",
        "title": "Food Safety and Standards (Ayurveda Aahar) Regulations, 2022",
        "shortTitle": "FSSAI Ayurveda Aahar Regulations 2022",
        "actRegulation": "Food Safety and Standards (Ayurveda Aahar) Regulations, 2022",
        "jurisdiction": "India",
        "authority": "Food Safety and Standards Authority of India (FSSAI)",
        "sourceUrl": "https://fssai.gov.in",
        "version": "F. No. Stds/SP-05/A-1.2022 / Gazette Notification",
        "year": "2022",
        "effectiveDate": "2022-05-05",
        "lastAmendedDate": "2022-05-05",
        "isLoaded": True,
        "sectionsCovered": ["Regulation 3 & Schedule IV", "Regulation 6"],
        "sections": [
            {
                "section": "Regulation 3 & Schedule IV",
                "sectionNumber": "Regulation 3 & Schedule IV",
                "title": "Definition & Scope of Ayurveda Aahar",
                "heading": "Definition & Scope of Ayurveda Aahar",
                "text": "Ayurveda Aahar means food prepared in accordance with the authoritative books of Ayurveda specified in Schedule A, used for dietary sustenance, general wellness, or lifestyle enhancement and NOT intended for treating or curing human diseases.",
                "keywords": ["ayurveda aahar", "fssai", "dietary supplement", "wellness food", "non-medicinal", "herbal tea", "schedule iv", "आयुर्वेद आहार"],
                "relevance": "Distinct regulatory pathway from Ayush drugs: regulated as specialized food by FSSAI.",
                "practicalImpact": "Cannot make therapeutic disease claims (cannot claim to 'cure diabetes', only 'supports normal glucose metabolism').",
                "authority": "Food Safety and Standards Authority of India (FSSAI)",
                "sourceUrl": "https://fssai.gov.in",
                "version": "FSSAI Regulation 2022 (F. No. Stds/SP-05/A-1.2022)",
                "effectiveDate": "2022-05-05",
                "lastAmendedDate": "2022-05-05"
            },
            {
                "section": "Regulation 6",
                "sectionNumber": "Regulation 6",
                "title": "Mandatory Ayurveda Aahar Logo & Statutory Warning",
                "heading": "Mandatory Ayurveda Aahar Logo & Statutory Warning",
                "text": "Every food business operator manufacturing or selling Ayurveda Aahar shall display the official Ayurveda Aahar Logo on the front of the pack, accompanied by the mandatory warning: 'FOR DIETARY USE ONLY - NOT FOR MEDICINAL USE'.",
                "keywords": ["logo", "statutory warning", "packaging", "labeling", "dietary use only", "not for medicinal use", "वैधानिक इशारा"],
                "relevance": "Strict packaging and labeling requirements to prevent consumer confusion with prescription Ayush medicines.",
                "practicalImpact": "Mandatory inclusion of green Ayurveda Aahar symbol and exact statutory advisory.",
                "authority": "Food Safety and Standards Authority of India (FSSAI)",
                "sourceUrl": "https://fssai.gov.in",
                "version": "FSSAI Regulation 2022 (Regulation 6)",
                "effectiveDate": "2022-05-05",
                "lastAmendedDate": "2022-05-05"
            }
        ]
    },
    {
        "id": "international_ayush_regimes",
        "title": "International Regulatory Frameworks for Herbal & Botanical Products",
        "shortTitle": "International Herbal Regimes (US FDA / EU EMA)",
        "actRegulation": "International Regulatory Frameworks for Herbal Products (US DSHEA / EU THMPD / Nagoya)",
        "jurisdiction": "International (US, EU, Global)",
        "authority": "US FDA (CDER/CFSAN), European Medicines Agency (EMA/HMPC), WHO, CBD Secretariat",
        "sourceUrl": "https://www.fda.gov/food/dietary-supplements",
        "version": "US 21 CFR 111 / Directive 2004/24/EC / Nagoya IRCC",
        "year": "2024",
        "effectiveDate": "1994-10-25",
        "lastAmendedDate": "2014-10-12",
        "isLoaded": True,
        "sectionsCovered": ["US FDA DSHEA & Botanical Drug Guidance", "EU THMPD 2004/24/EC", "Nagoya Protocol on ABS"],
        "sections": [
            {
                "section": "US FDA DSHEA & Botanical Drug Guidance",
                "sectionNumber": "US FDA DSHEA & Botanical Drug Guidance",
                "title": "Dietary Supplement vs Botanical Drug Pathway in the United States",
                "heading": "Dietary Supplement vs Botanical Drug Pathway in the United States",
                "text": "Under the Dietary Supplement Health and Education Act (DSHEA 1994), Ayurvedic herbs are marketed as dietary supplements with structure/function claims (no disease treatment claims). To market as a therapeutic drug, the sponsor must file an Investigational New Drug (IND) under FDA's Botanical Drug Development Guidance demonstrating batch-to-batch chemical fingerprint consistency and clinical efficacy.",
                "keywords": ["us fda", "dshea", "botanical drug guidance", "dietary supplement", "structure function", "ind", "export to usa", "fda compliance"],
                "relevance": "Most Ayurvedic exports to the US are marketed as dietary supplements to avoid multi-million dollar botanical drug trials.",
                "practicalImpact": "Must register food facility with FDA, comply with 21 CFR Part 111 cGMP, and include the standard FDA disclaimer.",
                "authority": "US FDA (Center for Drug Evaluation and Research / CFSAN)",
                "sourceUrl": "https://www.fda.gov/food/dietary-supplements",
                "version": "Public Law 103-417 (21 U.S.C. 321(ff)) & Guidance FDA-2000-D-0105",
                "effectiveDate": "1994-10-25",
                "lastAmendedDate": "2016-12-01"
            },
            {
                "section": "EU THMPD 2004/24/EC",
                "sectionNumber": "EU THMPD 2004/24/EC",
                "title": "Traditional Herbal Medicinal Products Directive (European Union)",
                "heading": "Traditional Herbal Medicinal Products Directive (European Union)",
                "text": "The Traditional Herbal Medicinal Products Directive allows simplified registration for herbal medicines that demonstrate 30 years of traditional medicinal use, of which at least 15 years must be documented within the European Union.",
                "keywords": ["eu thmpd", "european union", "ema", "traditional herbal", "15 years in eu", "simplified registration", "export to europe"],
                "relevance": "High barrier for new Ayurvedic formulations that lack 15 years of recorded European retail or clinical sales.",
                "practicalImpact": "Often classified and sold as Food Supplements in EU member states instead of medicinal products.",
                "authority": "European Medicines Agency (EMA) / HMPC",
                "sourceUrl": "https://www.ema.europa.eu/en/human-regulatory/herbal-medicinal-products",
                "version": "Directive 2004/24/EC amending Directive 2001/83/EC",
                "effectiveDate": "2004-04-30",
                "lastAmendedDate": "2011-04-30"
            },
            {
                "section": "Nagoya Protocol on ABS",
                "sectionNumber": "Nagoya Protocol on ABS",
                "title": "Nagoya Protocol on Access and Benefit Sharing (Global Compliance)",
                "heading": "Nagoya Protocol on Access and Benefit Sharing (Global Compliance)",
                "text": "An international agreement which aims at sharing the benefits arising from the utilization of genetic resources in a fair and equitable way. Requires internationally recognized certificates of compliance (IRCC) when utilizing foreign genetic material.",
                "keywords": ["nagoya protocol", "abs", "internationally recognized certificate", "ircc", "genetic resources", "cross-border bioprospecting"],
                "relevance": "Ensures that foreign entities commercializing traditional herbs respect sovereign rights and share benefits.",
                "practicalImpact": "Multinational patent filings must provide evidence of compliance with the provider country's national ABS law.",
                "authority": "Convention on Biological Diversity (CBD) Secretariat & National Focal Points",
                "sourceUrl": "https://absch.cbd.int",
                "version": "UNEP/CBD/COP/DEC/X/1 (Treaty entry into force)",
                "effectiveDate": "2014-10-12",
                "lastAmendedDate": "2014-10-12"
            }
        ]
    }
]

STATUTORY_KNOWLEDGE_RELATIONSHIPS: List[Dict[str, Any]] = [
    {
        "sourceSection": "Section 10(4)(d)(ii)",
        "sourceAct": "Patents Act 1970",
        "targetSection": "Section 6",
        "targetAct": "Biological Diversity Act 2002",
        "relationshipType": "MANDATORY_PRE_REQUISITE",
        "legalNexus": "Disclosure of Indian biological material origin in a patent specification triggers mandatory NBA Form III prior clearance before patent grant.",
        "jurisdiction": "India"
    },
    {
        "sourceSection": "Section 3(p)",
        "sourceAct": "Patents Act 1970",
        "targetSection": "Section 3(a)",
        "targetAct": "Drugs and Cosmetics Act 1940",
        "relationshipType": "PRIOR_ART_CROSS_REFERENCE",
        "legalNexus": "Formulations adhering strictly to the First Schedule Samhitas qualify for direct Ayush licensing under Section 3(a) but are barred from patentability under Section 3(p) as traditional knowledge prior art documented in TKDL.",
        "jurisdiction": "India"
    },
    {
        "sourceSection": "Section 3(e)",
        "sourceAct": "Patents Act 1970",
        "targetSection": "Rule 158B",
        "targetAct": "Drugs and Cosmetics Act 1940",
        "relationshipType": "EVIDENTIARY_PARALLEL",
        "legalNexus": "Novel Ayurvedic polyherbal proprietary medicines under Section 3(h) require safety and efficacy proof under Rule 158B, and require scientific proof of synergistic interaction (Combination Index < 1.0) to overcome Section 3(e) mere admixture rejections.",
        "jurisdiction": "India"
    },
    {
        "sourceSection": "Regulation 3 & Schedule IV",
        "sourceAct": "FSSAI Ayurveda Aahar Regulations 2022",
        "targetSection": "Section 3(a)",
        "targetAct": "Drugs and Cosmetics Act 1940",
        "relationshipType": "STATUTORY_BOUNDARY_DELIMITATION",
        "legalNexus": "Ayurveda Aahar products are restricted to dietary supplementation and general wellness; making curative or therapeutic disease treatment claims causes classification shift into Ayush Drug licensing under Section 3(a)/3(h).",
        "jurisdiction": "India"
    },
    {
        "sourceSection": "US FDA DSHEA & Botanical Drug Guidance",
        "sourceAct": "International Regimes",
        "targetSection": "Nagoya Protocol on ABS",
        "targetAct": "CBD Nagoya Protocol",
        "relationshipType": "CROSS_BORDER_COMPLIANCE",
        "legalNexus": "Exporting finished botanical products to the US under DSHEA requires FDA 21 CFR 111 cGMP compliance, while cross-border commercialization of genetic resources requires prior compliance with the source country's domestic ABS regime / IRCC.",
        "jurisdiction": "International"
    }
]
